from __future__ import annotations

import json
from pathlib import Path

from tools.color_fidelity import build_release_bundle
from tools.color_fidelity import run_audit


def _ok(title: str) -> run_audit.SectionResult:
    return run_audit.SectionResult(title, "body", run_audit.STATUS_OK)


def test_main_skip_live_marks_live_and_gamma_skipped(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setattr(run_audit, "section_channel_order", lambda: _ok("3 · Channel-order test"))
    monkeypatch.setattr(run_audit, "section_icc_embed", lambda: _ok("4 · ICC profile embedded (binary-verified)"))
    monkeypatch.setattr(run_audit, "section_chroma_subsampling", lambda _out: _ok("5 · Chroma subsampling sweep"))
    monkeypatch.setattr(run_audit, "section_jpeg_quality_pareto", lambda _q, _out: _ok("6 · JPEG quality Pareto"))
    monkeypatch.setattr(run_audit, "section_depth_roundtrip", lambda: _ok("7 · Depth decode round-trip"))
    monkeypatch.setattr(run_audit, "section_seg_palette", lambda: _ok("8 · Segmentation palette parity"))

    rc = run_audit.main(["--skip-live", "--skip-codecs", "--out", str(tmp_path)])

    assert rc == 0
    report = (tmp_path / "report.md").read_text()
    assert "- [SKIPPED] 1 · Raw sensor → server JPEG (wire-equivalent)" in report
    assert "- [SKIPPED] 2 · Gamma decision table" in report
    assert "Live capture skipped by `--skip-live`." in report
    assert "Live summary unavailable in this run" in report


def test_gamma_section_is_partial_for_wire_equivalent_fallback(tmp_path: Path) -> None:
    (tmp_path / "live_summary.json").write_text(
        json.dumps(
            {
                "psnr_p50": 53.55,
                "ssim_p50": 0.9976,
                "de_median_roi": 0.0,
                "mode": "wire_equivalent",
                "capture_subject": "spawned_fallback_vehicle",
                "fallback_vehicle": True,
            }
        )
    )

    section = run_audit.section_gamma_decision(tmp_path)

    assert section.status == run_audit.STATUS_PARTIAL
    assert "Numeric columns come from `wire_equivalent` evidence" in section.body_md
    assert "spawned_fallback_vehicle" in section.body_md


def test_section_live_discloses_fallback_vehicle(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setattr(
        run_audit,
        "_arm_bridge_session",
        lambda _host: {
            "carla_connected": True,
            "session_ready": True,
            "default_camera_id": 170,
            "state": "READY",
        },
    )
    monkeypatch.setattr(run_audit, "_probe_carla", lambda _host_port: True)
    monkeypatch.setattr(
        run_audit,
        "_capture_native_pipeline_pairs",
        lambda *_args, **_kwargs: (
            [{"path": tmp_path / "enc.jpg", "frame": 1, "timestamp": 0.0}],
            [{"path": tmp_path / "raw.png", "frame": 1, "timestamp": 0.0}],
            {"capture_subject": "spawned_fallback_vehicle", "fallback_vehicle": True},
        ),
    )
    monkeypatch.setattr(
        run_audit,
        "_pairwise_metrics",
        lambda *_args, **_kwargs: [
            {
                "idx": 0,
                "bridge_frame": 1,
                "native_frame": 1,
                "dt_ms": 0.0,
                "psnr": 50.0,
                "ssim": 0.99,
                "de_median_roi": 0.0,
                "de_mean_roi": 0.1,
                "de_p99_roi": 0.9,
                "per_ch_err": [0.0, 0.0, 0.0],
            }
        ],
    )

    args = run_audit.build_parser().parse_args(["--out", str(tmp_path)])
    section = run_audit.section_live(args, tmp_path)

    assert section.status == run_audit.STATUS_PARTIAL
    assert "capture subject: spawned_fallback_vehicle" in section.body_md
    assert "WARNING: this run used a spawned fallback vehicle" in section.body_md


def test_validate_report_structure_rejects_duplicate_and_out_of_order_sections() -> None:
    bad_report = "\n".join(
        [
            "## Summary",
            "## 10 · Limitations (audit does NOT cover)",
            "## 9 · Codec comparison (Pareto)",
            "## 10 · Limitations (audit does NOT cover)",
        ]
    )

    try:
        run_audit._validate_report_structure(bad_report)
    except ValueError as exc:
        msg = str(exc)
        assert "duplicate report sections" in msg or "out of order" in msg
    else:
        raise AssertionError("expected report structure validation to fail")


def test_build_release_bundle_marks_report_as_merged_and_orders_sections(tmp_path: Path) -> None:
    live = tmp_path / "live.md"
    codec = tmp_path / "codec.md"
    out = tmp_path / "bundle.md"
    live.write_text(
        "# Agent C\n"
        "_generated by `tools/color_fidelity/run_audit.py` at now_\n"
        "## Summary\n"
        "- [OK] 1 · Raw sensor → server JPEG (wire-equivalent)\n"
        "\n---\n\n"
        "## 1 · Raw sensor → server JPEG (wire-equivalent)\nbody1\n"
        "## 2 · Gamma decision table\nbody2\n"
        "## 3 · Channel-order test\nbody3\n"
        "## 4 · ICC profile embedded (binary-verified)\nbody4\n"
        "## 5 · Chroma subsampling sweep\nbody5\n"
        "## 6 · JPEG quality Pareto\nbody6\n"
        "## 7 · Depth decode round-trip\nbody7\n"
        "## 8 · Segmentation palette parity\nbody8\n"
        "## 10 · Limitations (audit does NOT cover)\nlimits\n"
    )
    codec.write_text(
        "# Agent C\n"
        "_generated by `tools/color_fidelity/run_audit.py` at later_\n"
        "## Summary\n"
        "- [OK] 9 · Codec comparison (Pareto)\n"
        "\n---\n\n"
        "## 9 · Codec comparison (Pareto)\ncodecbody\n"
        "## 10 · Limitations (audit does NOT cover)\notherlimits\n"
    )

    build_release_bundle.build_bundle(live, codec, out)
    text = out.read_text()

    assert "assembled from multiple verified reports" in text
    assert text.index("## 9 · Codec comparison (Pareto)") < text.index("## 10 · Limitations (audit does NOT cover)")
    assert text.count("## 10 · Limitations (audit does NOT cover)") == 1


def test_codec_compare_is_partial_when_browser_decode_is_unavailable(monkeypatch, tmp_path: Path) -> None:
    def fake_row(codec: str, variant: str, n: int = 5) -> dict:
        return {
            "codec": codec,
            "variant": variant,
            "n": n,
            "enc_ms_p50": 1.0,
            "enc_ms_p99": 2.0,
            "bytes_p50": 100,
            "bytes_p99": 100,
            "ssim": 0.99,
        }

    monkeypatch.setattr(run_audit.codec_bench, "make_reference", lambda: __import__("numpy").zeros((4, 4, 3), dtype="uint8"))
    monkeypatch.setattr(run_audit.codec_bench, "bench_jpeg", lambda *_args, **_kwargs: fake_row("JPEG", "q=85 ss=2"))
    monkeypatch.setattr(run_audit.codec_bench, "bench_webp", lambda *_args, **_kwargs: fake_row("WebP", "q=85"))
    monkeypatch.setattr(run_audit.codec_bench, "bench_avif", lambda *_args, **_kwargs: fake_row("AVIF", "q=65"))
    monkeypatch.setattr(run_audit.codec_bench, "bench_h264_keyframe", lambda *_args, **_kwargs: fake_row("H.264-key", "crf=22"))
    monkeypatch.setattr(run_audit, "_write_codec_sample", lambda out_dir, _src, codec, variant: out_dir / f"{codec}_{variant}.bin")
    monkeypatch.setattr(run_audit, "_write_pareto_plot", lambda *_args, **_kwargs: None)
    monkeypatch.setattr(run_audit, "_measure_browser_decode", lambda *_args, **_kwargs: {})

    section = run_audit.section_codec_compare(5, tmp_path)

    assert section.status == run_audit.STATUS_PARTIAL
    assert "only partially verified" in section.body_md
