"""Assemble an honest release bundle from separate verified reports.

This bundle is intentionally marked as a merged artifact. It is not a
single direct `run_audit.py` output.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_DIR.parent.parent))

from tools.color_fidelity.run_audit import _validate_report_structure


def _extract_section(text: str, title: str) -> str:
    marker = f"\n## {title}\n"
    if marker not in text:
        raise ValueError(f"section missing: {title}")
    tail = text.split(marker, 1)[1]
    next_idx = tail.find("\n## ")
    body = tail if next_idx < 0 else tail[:next_idx]
    return f"## {title}\n{body.rstrip()}\n"


def build_bundle(live_report: Path, codec_report: Path, out_report: Path) -> Path:
    live_text = live_report.read_text()
    codec_text = codec_report.read_text()

    prelude = live_text.split("\n## 1 · ", 1)[0]
    prelude = prelude.replace(
        "_generated by `tools/color_fidelity/run_audit.py`",
        "_assembled from multiple verified reports (not a single `run_audit.py` run)_\n"
        f"- source live/default report: `{live_report}`\n"
        f"- source codec report: `{codec_report}`\n\n_generated by `tools/color_fidelity/run_audit.py`",
        1,
    )
    prelude = prelude.replace(
        "- frames: `10`; codec frames: `100`\n",
        "- frames: `10`; codec frames: `merged` (see source codec report for sweep counts)\n",
    )

    sections = [
        _extract_section(live_text, "1 · Raw sensor → server JPEG (wire-equivalent)"),
        _extract_section(live_text, "2 · Gamma decision table"),
        _extract_section(live_text, "3 · Channel-order test"),
        _extract_section(live_text, "4 · ICC profile embedded (binary-verified)"),
        _extract_section(live_text, "5 · Chroma subsampling sweep"),
        _extract_section(live_text, "6 · JPEG quality Pareto"),
        _extract_section(live_text, "7 · Depth decode round-trip"),
        _extract_section(live_text, "8 · Segmentation palette parity"),
        _extract_section(codec_text, "9 · Codec comparison (Pareto)"),
        _extract_section(live_text, "10 · Limitations (audit does NOT cover)"),
    ]

    # Replace summary block with a merged-bundle summary.
    summary_lines = ["## Summary"]
    for idx, title in enumerate(
        [
            "1 · Raw sensor → server JPEG (wire-equivalent)",
            "2 · Gamma decision table",
            "3 · Channel-order test",
            "4 · ICC profile embedded (binary-verified)",
            "5 · Chroma subsampling sweep",
            "6 · JPEG quality Pareto",
            "7 · Depth decode round-trip",
            "8 · Segmentation palette parity",
            "9 · Codec comparison (Pareto)",
        ],
        start=1,
    ):
        summary_lines.append(f"- [MERGED] {title}")

    head, _ = prelude.split("## Summary", 1)
    report_text = head + "\n".join(summary_lines) + "\n\n---\n\n" + "\n".join(sections)
    _validate_report_structure(report_text)
    out_report.parent.mkdir(parents=True, exist_ok=True)
    out_report.write_text(report_text)
    return out_report


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="build_release_bundle")
    p.add_argument("--live-report", required=True)
    p.add_argument("--codec-report", required=True)
    p.add_argument("--out", required=True)
    args = p.parse_args(argv)
    path = build_bundle(Path(args.live_report), Path(args.codec_report), Path(args.out))
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
