#!/usr/bin/env python3
"""Color-fidelity comparison harness for the CARLA → browser pipeline.

Subcommands (all are self-contained unless noted):

    stats <three.png> <ue5.jpg>
        Legacy mode: sample both images and print per-channel / luminance
        / histogram deltas. Used by the rendering agent for quick visual
        parity checks.

    test-pattern [--backend auto|turbojpeg|pillow] [--quality 85]
        Synthetic BGRA → JPEG round-trip. Proves channel order, alpha
        handling, and chroma-subsampling behavior by encoding known
        patterns (pure R/G/B/K/W, a road-grey ramp, and a colored
        checkerboard) and checking decoded pixel values. Reports
        per-channel ΔE and ΔL.

    depth-roundtrip
        Numeric verification of the CARLA depth encoding. Picks 10 depths
        in [0, 1000 m], encodes to BGRA per CARLA's formula
        (ColorConverter.h:35-39), decodes via image.py, and asserts the
        recovered meters are within quantization tolerance.

    palette-diff
        Cross-checks src/compression/image.py's CITYSCAPES_PALETTE
        against LibCarla/.../CityScapesPalette.h by parsing the header.
        Fails non-zero if any entry drifts.

    jpeg-sweep [--quality 60,75,85,95] [--input ue5.png]
        Encodes the same reference image at several quality levels with
        both 4:2:0 and 4:4:4 chroma subsampling (Pillow), reports
        bytes and SSIM vs. the source, and writes a CSV.

    live  [--bridge ws://HOST:PORT/ws] [--carla HOST:PORT] [--frames N]
        Run the Agent-C audit driver and emit the same `report.md`
        generated by `tools/color_fidelity/run_audit.py`. The current
        live path measures raw CARLA BGRA frames against the exact server
        JPEG encoder path (wire-equivalent to the bytes sent after
        `sensor_manager._encode_camera_packet()`), then adds the offline
        JPEG / depth / palette / codec sections.

    match-frustum [--camera-id N] [--frames N]
        Pause the sim, load the browser with `?camPose=<source-camera-world-pose>`,
        capture the Three.js viewport canvas, and compare it against a shadow
        native RGB camera spawned at the same pose as the managed camera actor.
        Current scope is intentionally narrow: managed RGB camera only.

    regress --baseline old.csv --new new.csv
        Compare two CSV outputs (for example from `match-frustum`) and fail
        when any tracked metric regresses beyond the configured tolerance.

Run subcommands with -h for per-command flags.
"""
from __future__ import annotations

import argparse
import colorsys
import csv
import json
import math
import os
import re
import statistics
import subprocess
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path
from typing import Iterable

from PIL import Image

THIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = THIS_DIR.parent.parent
BRIDGE_SRC = THIS_DIR.parent / "src"
BRIDGE_VENV_PYTHON = THIS_DIR.parent / ".venv" / "bin" / "python"
CARLA_HEADER = (
    REPO_ROOT / "LibCarla" / "source" / "carla" / "image" / "CityScapesPalette.h"
)

# Allow importing src.* without installing the package.
sys.path.insert(0, str(THIS_DIR.parent))


# ============================================================================
# Legacy stats subcommand (kept from the rendering agent)
# ============================================================================


def _sample(im: Image.Image, stride: int = 50) -> list[tuple[int, int, int]]:
    im = im.convert("RGB")
    return list(im.getdata())[::stride]


def _stats(name: str, px: Iterable[tuple[int, int, int]]) -> dict[str, float]:
    pxl = list(px)
    n = len(pxl)
    r = [p[0] for p in pxl]
    g = [p[1] for p in pxl]
    b = [p[2] for p in pxl]
    lum = [0.299 * p[0] + 0.587 * p[1] + 0.114 * p[2] for p in pxl]
    sat = []
    for pr, pg, pb in pxl:
        _, s, _ = colorsys.rgb_to_hsv(pr / 255, pg / 255, pb / 255)
        sat.append(s)
    buckets = {
        "dark<50": sum(1 for x in lum if x < 50) / n,
        "mid50-125": sum(1 for x in lum if 50 <= x < 125) / n,
        "mid125-200": sum(1 for x in lum if 125 <= x < 200) / n,
        "bright>=200": sum(1 for x in lum if x >= 200) / n,
    }
    return {
        "name": name,
        "n": n,
        "meanR": statistics.mean(r),
        "meanG": statistics.mean(g),
        "meanB": statistics.mean(b),
        "meanLum": statistics.mean(lum),
        "stdLum": statistics.stdev(lum) if n > 1 else 0.0,
        "meanSat": statistics.mean(sat),
        **buckets,
    }


def _fmt(d: dict[str, float]) -> str:
    keys = [
        "name", "meanR", "meanG", "meanB", "meanLum", "stdLum", "meanSat",
        "dark<50", "mid50-125", "mid125-200", "bright>=200",
    ]
    out = []
    for k in keys:
        v = d[k]
        out.append(f"{k}={v:.3f}" if isinstance(v, float) else f"{k}={v}")
    return "  ".join(out)


def _delta(a: dict[str, float], b: dict[str, float]) -> str:
    keys = [
        "meanR", "meanG", "meanB", "meanLum", "stdLum", "meanSat",
        "dark<50", "mid50-125", "mid125-200", "bright>=200",
    ]
    return "  ".join(f"Δ{k}={b[k] - a[k]:+.3f}" for k in keys)


def cmd_stats(args: argparse.Namespace) -> int:
    three_path = Path(args.threejs_png)
    ue5_path = Path(args.ue5_jpg)
    three = _stats("three", _sample(Image.open(three_path)))
    ue5 = _stats("ue5", _sample(Image.open(ue5_path)))
    print(_fmt(three))
    print(_fmt(ue5))
    print("DELTA (three − ue5):", _delta(ue5, three))
    return 0


# ============================================================================
# Color-space helpers (sRGB → linear → XYZ → Lab → ΔE*76)
# ============================================================================


def _srgb_to_linear(x: float) -> float:
    x /= 255.0
    return x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4


def _linear_to_xyz(r: float, g: float, b: float) -> tuple[float, float, float]:
    # D65 matrix
    X = r * 0.4124564 + g * 0.3575761 + b * 0.1804375
    Y = r * 0.2126729 + g * 0.7151522 + b * 0.0721750
    Z = r * 0.0193339 + g * 0.1191920 + b * 0.9503041
    return X, Y, Z


def _f_lab(t: float) -> float:
    delta = 6.0 / 29.0
    if t > delta ** 3:
        return t ** (1.0 / 3.0)
    return t / (3.0 * delta * delta) + 4.0 / 29.0


def rgb_to_lab(r: int, g: int, b: int) -> tuple[float, float, float]:
    rl = _srgb_to_linear(r)
    gl = _srgb_to_linear(g)
    bl = _srgb_to_linear(b)
    X, Y, Z = _linear_to_xyz(rl, gl, bl)
    # D65 white
    Xn, Yn, Zn = 0.95047, 1.00000, 1.08883
    fx = _f_lab(X / Xn)
    fy = _f_lab(Y / Yn)
    fz = _f_lab(Z / Zn)
    L = 116 * fy - 16
    a = 500 * (fx - fy)
    bb = 200 * (fy - fz)
    return L, a, bb


def delta_e_76(p: tuple[int, int, int], q: tuple[int, int, int]) -> float:
    Lp, ap, bp = rgb_to_lab(*p)
    Lq, aq, bq = rgb_to_lab(*q)
    return math.sqrt((Lp - Lq) ** 2 + (ap - aq) ** 2 + (bp - bq) ** 2)


# ============================================================================
# Shared helpers for live/browser capture
# ============================================================================


def _http_json(url: str, *, method: str = "GET", payload: dict | None = None, timeout: float = 15.0):
    data = None
    headers = {}
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _http_post_json(url: str, payload: dict, *, timeout: float = 15.0):
    return _http_json(url, method="POST", payload=payload, timeout=timeout)


def _poll_json(url: str, predicate, *, timeout_s: float = 45.0, interval_s: float = 1.0):
    deadline = time.monotonic() + timeout_s
    last = None
    while time.monotonic() < deadline:
        try:
            last = _http_json(url, timeout=max(2.0, interval_s + 1.0))
            if predicate(last):
                return last
        except Exception:
            pass
        time.sleep(interval_s)
    if last is None:
        raise TimeoutError(f"Timed out polling {url}")
    raise TimeoutError(f"Timed out waiting for predicate on {url}; last={last}")


def _luma_hist_intersection(a, b, bins: int = 64) -> float:
    import numpy as np

    a_l = 0.2126 * a[..., 0] + 0.7152 * a[..., 1] + 0.0722 * a[..., 2]
    b_l = 0.2126 * b[..., 0] + 0.7152 * b[..., 1] + 0.0722 * b[..., 2]
    hist_a, _ = np.histogram(a_l, bins=bins, range=(0, 255), density=False)
    hist_b, _ = np.histogram(b_l, bins=bins, range=(0, 255), density=False)
    hist_a = hist_a.astype(np.float64)
    hist_b = hist_b.astype(np.float64)
    if hist_a.sum() == 0 or hist_b.sum() == 0:
        return 0.0
    hist_a /= hist_a.sum()
    hist_b /= hist_b.sum()
    return float(np.minimum(hist_a, hist_b).sum())


def _image_metrics(web_path: Path, ue5_path: Path) -> dict[str, float | int | str]:
    import numpy as np

    from tools.color_fidelity import color as cf_color
    from tools.color_fidelity import metrics as cf_metrics

    web = np.asarray(Image.open(web_path).convert("RGB"), dtype=np.uint8)
    ue5 = np.asarray(Image.open(ue5_path).convert("RGB"), dtype=np.uint8)
    if web.shape != ue5.shape:
        height = min(web.shape[0], ue5.shape[0])
        width = min(web.shape[1], ue5.shape[1])
        web = web[:height, :width]
        ue5 = ue5[:height, :width]

    de = cf_color.delta_e_76(web, ue5)
    per_channel = (web.astype(np.float32) - ue5.astype(np.float32)).reshape(-1, 3).mean(axis=0)
    return {
        "width": int(web.shape[1]),
        "height": int(web.shape[0]),
        "deltae76_mean_full_frame": float(de.mean()),
        "deltae76_p95_full_frame": float(np.percentile(de, 95)),
        "ssim_luma": float(cf_metrics.ssim(web, ue5)),
        "psnr_db": float(cf_metrics.psnr(web, ue5)),
        "hist_intersection_luma_64": _luma_hist_intersection(web, ue5, bins=64),
        "mean_err_r": float(per_channel[0]),
        "mean_err_g": float(per_channel[1]),
        "mean_err_b": float(per_channel[2]),
        "web_path": str(web_path),
        "ue5_path": str(ue5_path),
    }


def _target_failures(metrics: dict[str, float | int | str]) -> list[str]:
    failures: list[str] = []
    if float(metrics["deltae76_mean_full_frame"]) > 1.0:
        failures.append("deltae76_mean_full_frame>1.0")
    if float(metrics["deltae76_p95_full_frame"]) > 3.0:
        failures.append("deltae76_p95_full_frame>3.0")
    if float(metrics["ssim_luma"]) < 0.97:
        failures.append("ssim_luma<0.97")
    if float(metrics["psnr_db"]) < 32.0:
        failures.append("psnr_db<32.0")
    if float(metrics["hist_intersection_luma_64"]) < 0.92:
        failures.append("hist_intersection_luma_64<0.92")
    return failures


def _capture_browser_canvas(
    *,
    page_url: str,
    out_path: Path,
    debug_key: str,
    wait_ms: int = 2500,
    timeout_ms: int = 20000,
) -> dict:
    out_path = out_path.resolve()
    meta_path = out_path.with_suffix(out_path.suffix + ".json")
    script = r"""
const fs = require('fs');
const path = require('path');

function loadPlaywright() {
  const candidates = [
    'playwright',
    path.resolve(process.cwd(), '../carla-web/node_modules/playwright'),
    path.resolve(process.cwd(), '../.omx/browser-decode/node_modules/playwright'),
    path.resolve(process.cwd(), '../../carla-web/node_modules/playwright'),
    path.resolve(process.cwd(), '../../.omx/browser-decode/node_modules/playwright'),
  ];
  for (const candidate of candidates) {
    try { return require(candidate); } catch {}
  }
  throw new Error(`playwright module not found in candidates: ${candidates.join(', ')}`);
}

const { chromium } = loadPlaywright();
const url = process.env.COMPARE_RENDER_URL;
const outPath = process.env.COMPARE_RENDER_OUT;
const metaPath = process.env.COMPARE_RENDER_META;
const selector = process.env.COMPARE_RENDER_SELECTOR;
const debugKey = process.env.COMPARE_RENDER_DEBUG_KEY || '';
const waitMsRaw = process.env.COMPARE_RENDER_WAIT_MS;
const timeoutMsRaw = process.env.COMPARE_RENDER_TIMEOUT_MS;
const waitMs = Number.parseInt(waitMsRaw, 10);
const timeoutMs = Number.parseInt(timeoutMsRaw, 10);

(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'domcontentloaded', timeout: timeoutMs });
  await page.waitForTimeout(Math.max(waitMs, 8000));
  const capture = await page.evaluate(({ selector, debugKey }) => {
    const tagged = document.querySelector(selector);
    const canvas =
      tagged instanceof HTMLCanvasElement
        ? tagged
        : tagged instanceof HTMLElement
          ? tagged.querySelector('canvas')
          : Array.from(document.querySelectorAll('canvas')).sort((a, b) => (b.width * b.height) - (a.width * a.height))[0];
    if (!(canvas instanceof HTMLCanvasElement)) {
      throw new Error(`canvas not found for selector ${selector}`);
    }
    return {
      width: canvas.width,
      height: canvas.height,
      dataUrl: canvas.toDataURL('image/png'),
      debug: debugKey ? window[debugKey] ?? null : null,
    };
  }, { selector, debugKey });
  const base64 = capture.dataUrl.replace(/^data:image\/png;base64,/, '');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, Buffer.from(base64, 'base64'));
  fs.writeFileSync(metaPath, JSON.stringify({ path: outPath, width: capture.width, height: capture.height, selector, debug: capture.debug }));
  console.log(JSON.stringify({ path: outPath, width: capture.width, height: capture.height, selector, debug: capture.debug }));
  browser.close().catch(() => {});
})().catch((err) => {
  console.error(err.stack || String(err));
  process.exit(1);
});
"""
    bash_script = """node - <<'EOF'
""" + script + """
EOF"""
    env = os.environ.copy()
    env.update(
        {
            "COMPARE_RENDER_URL": page_url,
            "COMPARE_RENDER_OUT": str(out_path),
            "COMPARE_RENDER_META": str(meta_path),
            "COMPARE_RENDER_SELECTOR": "[data-screenshot-target]",
            "COMPARE_RENDER_DEBUG_KEY": debug_key,
            "COMPARE_RENDER_WAIT_MS": str(wait_ms),
            "COMPARE_RENDER_TIMEOUT_MS": str(timeout_ms),
        }
    )
    if out_path.exists():
        out_path.unlink()
    if meta_path.exists():
        meta_path.unlink()
    proc = None
    try:
        proc = subprocess.Popen(
            ["bash", "-lc", bash_script],
            cwd=THIS_DIR.parent,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        deadline = time.monotonic() + max(30.0, timeout_ms / 1000.0 + 10.0)
        while time.monotonic() < deadline:
            if meta_path.exists() and out_path.exists() and out_path.stat().st_size > 0:
                break
            if proc.poll() is not None:
                stdout, stderr = proc.communicate(timeout=1)
                raise RuntimeError(
                    f"browser capture failed rc={proc.returncode}: {(stderr or stdout).strip()}"
                )
            time.sleep(0.25)
        else:
            raise RuntimeError(f"browser capture timed out after {max(30.0, timeout_ms / 1000.0 + 10.0)}s")

        try:
            proc.terminate()
            proc.wait(timeout=2)
        except Exception:
            try:
                proc.kill()
            except Exception:
                pass

        return json.loads(meta_path.read_text())
    finally:
        if proc is not None and proc.poll() is None:
            try:
                proc.kill()
            except Exception:
                pass
        try:
            meta_path.unlink(missing_ok=True)
        except Exception:
            pass


def _capture_native_shadow_frames(
    *,
    carla_host_port: str,
    source_camera_id: int,
    frames: int,
    out_dir: Path,
) -> list[dict]:
    import numpy as np

    try:
        import carla  # type: ignore
    except Exception as exc:  # pragma: no cover - live-only
        raise RuntimeError(f"carla module not importable: {exc}") from exc

    host, port = carla_host_port.split(":")
    client = carla.Client(host, int(port))
    client.set_timeout(10.0)
    world = client.get_world()
    source_actor = world.get_actor(int(source_camera_id))
    if source_actor is None:
        raise RuntimeError(f"camera actor {source_camera_id} not found in CARLA world")

    bp_lib = world.get_blueprint_library()
    cam_bp = bp_lib.find("sensor.camera.rgb")
    copied = {}
    for key in (
        "image_size_x",
        "image_size_y",
        "fov",
        "sensor_tick",
        "enable_postprocess_effects",
    ):
        value = source_actor.attributes.get(key)
        if value and cam_bp.has_attribute(key):
            cam_bp.set_attribute(key, value)
            copied[key] = value
    if cam_bp.has_attribute("role_name"):
        cam_bp.set_attribute("role_name", "compare_render_shadow")

    sensor = world.spawn_actor(cam_bp, source_actor.get_transform())
    saved: list[dict] = []
    target_frames = max(1, int(frames))

    def _on_image(img) -> None:
        if len(saved) >= target_frames:
            return
        arr = np.frombuffer(img.raw_data, dtype=np.uint8).reshape(img.height, img.width, 4)
        rgb = arr[:, :, [2, 1, 0]]
        out_path = out_dir / f"ue5_{len(saved):03d}.png"
        Image.fromarray(rgb, "RGB").save(out_path)
        saved.append(
            {
                "frame": int(img.frame),
                "timestamp": float(img.timestamp),
                "path": out_path,
                "width": int(img.width),
                "height": int(img.height),
                "copied_attrs": copied,
            }
        )

    sensor.listen(_on_image)
    try:
        settings = world.get_settings()
        deadline = time.monotonic() + max(10.0, target_frames * 2.0)
        while len(saved) < target_frames and time.monotonic() < deadline:
            if settings.synchronous_mode:
                world.tick()
            else:  # pragma: no cover - current live stack uses sync pause
                world.wait_for_tick(1.0)
            time.sleep(0.05)
        if len(saved) < target_frames:
            raise TimeoutError(
                f"captured {len(saved)}/{target_frames} native frames from source camera {source_camera_id}"
            )
    finally:
        sensor.stop()
        sensor.destroy()
    return saved


def _source_camera_pose(carla_host_port: str, camera_id: int) -> tuple[float, float, float, float, float, float]:
    try:
        import carla  # type: ignore
    except Exception as exc:  # pragma: no cover - live-only
        raise RuntimeError(f"carla module not importable: {exc}") from exc

    host, port = carla_host_port.split(":")
    client = carla.Client(host, int(port))
    client.set_timeout(10.0)
    world = client.get_world()
    source_actor = world.get_actor(int(camera_id))
    if source_actor is None:
        raise RuntimeError(f"camera actor {camera_id} not found in CARLA world")
    tf = source_actor.get_transform()
    return (
        float(tf.location.x),
        float(tf.location.y),
        float(tf.location.z),
        float(tf.rotation.yaw),
        float(tf.rotation.pitch),
        float(tf.rotation.roll),
    )


def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def _regression_failures(
    baseline_rows: list[dict[str, str]],
    new_rows: list[dict[str, str]],
    *,
    deltae_mean_tol: float = 0.0,
    deltae_p95_tol: float = 0.0,
    ssim_tol: float = 0.0,
    psnr_tol: float = 0.0,
    hist_tol: float = 0.0,
) -> list[str]:
    key_cols = [col for col in ("map", "pose", "weather", "tod", "frame", "camera_id") if baseline_rows and col in baseline_rows[0]]
    if not key_cols:
        key_cols = [col for col in ("frame", "camera_id") if new_rows and col in new_rows[0]]
    metric_cols = {
        "deltae76_mean_full_frame": ("max", deltae_mean_tol),
        "deltae76_p95_full_frame": ("max", deltae_p95_tol),
        "ssim_luma": ("min", ssim_tol),
        "psnr_db": ("min", psnr_tol),
        "hist_intersection_luma_64": ("min", hist_tol),
    }
    baseline_by_key = {tuple(row.get(col, "") for col in key_cols): row for row in baseline_rows}
    new_keys = {tuple(row.get(col, "") for col in key_cols) for row in new_rows}
    failures: list[str] = []
    for key in baseline_by_key:
        if key not in new_keys:
            failures.append(f"missing new row for key={key}")
    for row in new_rows:
        key = tuple(row.get(col, "") for col in key_cols)
        baseline = baseline_by_key.get(key)
        if baseline is None:
            failures.append(f"missing baseline row for key={key}")
            continue
        for metric, (direction, tolerance) in metric_cols.items():
            if metric not in baseline or metric not in row:
                failures.append(f"metric {metric} missing for key={key}")
                continue
            before = float(baseline[metric])
            after = float(row[metric])
            if direction == "max" and after > before + tolerance:
                failures.append(
                    f"{metric} regressed for key={key}: baseline={before:.6f} new={after:.6f} tol={tolerance:.6f}"
                )
            if direction == "min" and after < before - tolerance:
                failures.append(
                    f"{metric} regressed for key={key}: baseline={before:.6f} new={after:.6f} tol={tolerance:.6f}"
                )
    return failures


def _maybe_reexec_bridge_python() -> None:
    if os.environ.get("COMPARE_RENDER_VENV_REEXEC") == "1":
        return
    if not BRIDGE_VENV_PYTHON.exists():
        return
    try:
        current = Path(sys.executable).resolve()
        target = BRIDGE_VENV_PYTHON.resolve()
    except Exception:
        return
    if current == target:
        return
    env = os.environ.copy()
    env["COMPARE_RENDER_VENV_REEXEC"] = "1"
    result = subprocess.run(
        [str(target), str(Path(__file__).resolve()), *sys.argv[1:]],
        cwd=REPO_ROOT,
        env=env,
        check=False,
    )
    raise SystemExit(result.returncode)


# ============================================================================
# test-pattern — proves BGRA→JPEG channel order, alpha, subsampling
# ============================================================================


def _make_bgra(pixels: list[list[tuple[int, int, int, int]]]) -> bytes:
    import numpy as np

    arr = np.array(pixels, dtype=np.uint8)
    assert arr.shape[2] == 4, "need BGRA"
    return arr.tobytes()


def _decode_jpeg(jpg: bytes) -> "any":
    import numpy as np

    img = Image.open(BytesIO(jpg)).convert("RGB")
    return np.asarray(img, dtype=np.uint8)


def cmd_test_pattern(args: argparse.Namespace) -> int:
    import numpy as np

    # Force backend if requested
    import os

    os.environ["JPEG_BACKEND"] = args.backend

    from src.compression.image import image_compressor  # noqa: E402

    W, H = 32, 32
    # Pattern A: solid primary colors in BGRA, 8×8 each
    # Expected RGB after decode: R=[255,0,0], G=[0,255,0], B=[0,0,255], K=[0,0,0]
    patches = {
        "red":   (0, 0, 255, 255),   # B=0 G=0 R=255
        "green": (0, 255, 0, 255),   # B=0 G=255 R=0
        "blue":  (255, 0, 0, 255),   # B=255 G=0 R=0
        "black": (0, 0, 0, 255),
        "white": (255, 255, 255, 255),
        "road":  (64, 64, 64, 255),  # neutral grey — the literal "road" test
        # These alpha values should be IGNORED (we drop alpha at RGB conversion)
        "alpha_check": (128, 200, 50, 0),  # alpha=0 must not show through
    }
    pixels: list[list[tuple[int, int, int, int]]] = []
    rows_per_patch = H // len(patches)
    names = list(patches.keys())
    for y in range(H):
        name = names[min(y // rows_per_patch, len(names) - 1)]
        pixels.append([patches[name]] * W)
    raw = _make_bgra(pixels)

    # Use quality=95 so compression noise is small enough to prove identity
    jpg = image_compressor.compress_bgra_to_jpeg(raw, W, H, quality=95)
    decoded = _decode_jpeg(jpg)
    print(f"# backend={args.backend} quality=95 input_bytes={len(raw)} "
          f"jpeg_bytes={len(jpg)} (ratio {len(raw) / max(len(jpg), 1):.2f}×)")

    # Check each patch's center pixel
    print(f"{'patch':<12}{'expected_rgb':<20}{'got_rgb':<20}{'ΔE76':>8}")
    print("-" * 60)
    max_delta = 0.0
    for i, name in enumerate(names):
        b, g, r, a = patches[name]
        expected = (r, g, b)
        y_center = i * rows_per_patch + rows_per_patch // 2
        got = tuple(int(x) for x in decoded[y_center, W // 2])
        de = delta_e_76(expected, got)
        max_delta = max(max_delta, de)
        flag = "" if de < 3.0 else "  <— drift"
        print(f"{name:<12}{str(expected):<20}{str(got):<20}{de:>8.2f}{flag}")

    # Explicit channel-swap assertion: red patch must decode to RGB with R
    # dominant, NOT B. If they ever swap, this will blow up loud.
    red_center = decoded[rows_per_patch // 2, W // 2]
    assert red_center[0] > red_center[2] + 100, (
        f"RED patch decoded as {red_center!r} — channel order is WRONG "
        f"(expected R≫B, got R={red_center[0]} B={red_center[2]})"
    )
    print(f"\nmax_ΔE76={max_delta:.2f}  channel_order=OK")
    return 0 if max_delta < 3.0 else 1


# ============================================================================
# depth-roundtrip — verifies CARLA depth decode formula
# ============================================================================


def cmd_depth_roundtrip(_args: argparse.Namespace) -> int:
    import numpy as np

    from src.compression.image import image_compressor  # noqa

    # Replicate CARLA's encode (inverse of ColorConverter.h::Depth):
    # normalized = meters / 1000
    # code = normalized * (256^3 - 1)
    # R = code & 0xff ; G = (code >> 8) & 0xff ; B = (code >> 16) & 0xff
    depths_m = [0.0, 0.5, 1.0, 5.0, 25.0, 100.0, 250.0, 500.0, 999.0, 1000.0]

    print(f"{'meters':>8}  {'encoded_BGRA':<18}  "
          f"{'decoded_norm':>13}  {'recovered_m':>12}  {'abs_err_m':>10}")
    max_err = 0.0
    for m in depths_m:
        normalized = m / 1000.0
        code = int(normalized * (256 ** 3 - 1))
        R = code & 0xFF
        G = (code >> 8) & 0xFF
        B = (code >> 16) & 0xFF

        # Build a 1x1 BGRA buffer and feed the image.py depth decode math
        # (we replicate the math here since apply_depth_colormap outputs JPEG
        # bytes, not the scalar — the math is identical to image.py:91-95).
        r_f, g_f, b_f = float(R), float(G), float(B)
        normalized_decoded = (r_f + g_f * 256.0 + b_f * 65536.0) / (256.0 ** 3 - 1.0)
        recovered_m = normalized_decoded * 1000.0
        err = abs(recovered_m - m)
        max_err = max(max_err, err)
        print(f"{m:>8.2f}  B={B:<3} G={G:<3} R={R:<3}    "
              f"{normalized_decoded:>13.8f}  {recovered_m:>12.4f}  {err:>10.2e}")

    # Quantization bound: one LSB of the R channel ≈ 1000 / (2^24 - 1) m
    lsb_m = 1000.0 / (256 ** 3 - 1)
    print(f"\ntheoretical_lsb_m={lsb_m:.3e}  max_err_m={max_err:.3e}")

    # Allow a couple of LSBs slack for float rounding
    if max_err > 3 * lsb_m:
        print("FAIL: decode error exceeds 3×LSB quantization bound")
        return 1
    print("OK: depth decode matches CARLA's ColorConverter.h::Depth within quantization.")
    return 0


# ============================================================================
# palette-diff — CITYSCAPES_PALETTE vs LibCarla/.../CityScapesPalette.h
# ============================================================================


@dataclass
class PaletteEntry:
    idx: int
    name: str
    rgb: tuple[int, int, int]


def _parse_carla_header(path: Path) -> list[PaletteEntry]:
    text = path.read_text()
    # Match `{R,G,B},` followed by a `// name  =  Nu` comment. Example:
    #     {128u,  64u, 128u},   // road          =   1u
    pat = re.compile(
        r"\{\s*(\d+)u?,\s*(\d+)u?,\s*(\d+)u?\s*\},\s*//\s*([A-Za-z ]+?)\s*=\s*(\d+)u"
    )
    entries = []
    for m in pat.finditer(text):
        r, g, b = int(m.group(1)), int(m.group(2)), int(m.group(3))
        name = m.group(4).strip()
        idx = int(m.group(5))
        entries.append(PaletteEntry(idx, name, (r, g, b)))
    entries.sort(key=lambda e: e.idx)
    return entries


def cmd_palette_diff(_args: argparse.Namespace) -> int:
    from src.compression.image import CITYSCAPES_PALETTE  # noqa

    if not CARLA_HEADER.exists():
        print(f"ERROR: CARLA header not found at {CARLA_HEADER}")
        return 2

    carla_entries = _parse_carla_header(CARLA_HEADER)
    print(f"CARLA header defines {len(carla_entries)} classes; bridge palette has {len(CITYSCAPES_PALETTE)}.")
    mismatches = 0
    for e in carla_entries:
        if e.idx >= len(CITYSCAPES_PALETTE):
            print(f"MISSING idx={e.idx:>2} {e.name:<14} carla_rgb={e.rgb}")
            mismatches += 1
            continue
        ours = tuple(int(x) for x in CITYSCAPES_PALETTE[e.idx])
        status = "OK  " if ours == e.rgb else "DIFF"
        if ours != e.rgb:
            mismatches += 1
        print(f"{status} idx={e.idx:>2} {e.name:<14} carla={e.rgb} ours={ours}")

    if len(CITYSCAPES_PALETTE) > len(carla_entries):
        for extra_idx in range(len(carla_entries), len(CITYSCAPES_PALETTE)):
            ours = tuple(int(x) for x in CITYSCAPES_PALETTE[extra_idx])
            print(f"EXTRA idx={extra_idx:>2} (not in header) ours={ours}")
            mismatches += 1

    print(f"\nmismatches={mismatches}")
    return 0 if mismatches == 0 else 1


# ============================================================================
# jpeg-sweep — quality / chroma-subsampling curve
# ============================================================================


def _ssim_gray(a, b) -> float:
    # Simple single-window SSIM on luminance. Good enough for a curve;
    # skimage.metrics.structural_similarity is preferred if present.
    import numpy as np

    try:
        from skimage.metrics import structural_similarity

        return float(structural_similarity(a, b, data_range=255))
    except Exception:
        pass
    # Fallback: global MSSIM-ish
    a = a.astype("float64")
    b = b.astype("float64")
    mu_a = a.mean()
    mu_b = b.mean()
    var_a = a.var()
    var_b = b.var()
    cov = ((a - mu_a) * (b - mu_b)).mean()
    c1 = (0.01 * 255) ** 2
    c2 = (0.03 * 255) ** 2
    num = (2 * mu_a * mu_b + c1) * (2 * cov + c2)
    den = (mu_a ** 2 + mu_b ** 2 + c1) * (var_a + var_b + c2)
    return float(num / den) if den != 0 else 0.0


def cmd_jpeg_sweep(args: argparse.Namespace) -> int:
    import numpy as np

    qualities = [int(x) for x in args.quality.split(",")]
    source = Path(args.input) if args.input else None

    if source and source.exists():
        src_img = Image.open(source).convert("RGB")
    else:
        # Synthetic: road-surface speckle, white + yellow lane markings,
        # a red stop line, and a colored traffic sign patch. The yellow
        # and red are the chroma-heavy elements that expose 4:2:0
        # subsampling damage; pure grey (which the first version used)
        # cannot — that's why the SSIM curve came out flat.
        rng = np.random.default_rng(42)
        H, W = 240, 640
        asphalt = rng.integers(45, 75, size=(H, W, 3), dtype=np.uint8)
        # white lane line (center)
        asphalt[H // 2 - 3:H // 2 + 3, 100:-100, :] = 235
        # yellow solid line (upper third) — RGB ≈ (255, 210, 30)
        asphalt[H // 3 - 2:H // 3 + 2, 50:-50, 0] = 255
        asphalt[H // 3 - 2:H // 3 + 2, 50:-50, 1] = 210
        asphalt[H // 3 - 2:H // 3 + 2, 50:-50, 2] = 30
        # red stop line (lower third)
        asphalt[2 * H // 3 - 2:2 * H // 3 + 2, 100:-100, 0] = 200
        asphalt[2 * H // 3 - 2:2 * H // 3 + 2, 100:-100, 1] = 20
        asphalt[2 * H // 3 - 2:2 * H // 3 + 2, 100:-100, 2] = 20
        # traffic sign patch (upper-right) — saturated blue
        asphalt[10:40, W - 80:W - 20, 0] = 30
        asphalt[10:40, W - 80:W - 20, 1] = 90
        asphalt[10:40, W - 80:W - 20, 2] = 220
        src_img = Image.fromarray(asphalt, "RGB")

    src_arr = np.asarray(src_img, dtype=np.uint8)
    gray = src_arr.mean(axis=-1)
    rows = []
    print(f"{'quality':>7}  {'subsample':<9}  {'bytes':>8}  "
          f"{'SSIM_Y':>7}  {'ΔE_mean':>8}  {'ΔE_p99':>8}")
    for q in qualities:
        for subsampling, label in [(0, "4:4:4"), (2, "4:2:0")]:
            buf = BytesIO()
            src_img.save(buf, format="JPEG", quality=q, subsampling=subsampling)
            data = buf.getvalue()
            dec = np.asarray(Image.open(BytesIO(data)).convert("RGB"))
            ssim = _ssim_gray(gray, dec.mean(axis=-1))

            # Pixel-sampled ΔE76 on a row subset to keep this cheap
            step = 11
            flat_src = src_arr[::step, ::step].reshape(-1, 3)
            flat_dec = dec[::step, ::step].reshape(-1, 3)
            des = [
                delta_e_76(tuple(int(x) for x in s), tuple(int(x) for x in d))
                for s, d in zip(flat_src, flat_dec)
            ]
            de_mean = float(np.mean(des))
            de_p99 = float(np.percentile(des, 99))
            rows.append({
                "quality": q, "subsampling": label,
                "bytes": len(data), "ssim": ssim,
                "de_mean": de_mean, "de_p99": de_p99,
            })
            print(f"{q:>7}  {label:<9}  {len(data):>8}  "
                  f"{ssim:>7.4f}  {de_mean:>8.3f}  {de_p99:>8.3f}")

    if args.csv:
        out_path = Path(args.csv)
        with out_path.open("w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=[
                "quality", "subsampling", "bytes", "ssim", "de_mean", "de_p99",
            ])
            w.writeheader()
            w.writerows(rows)
        print(f"\nwrote {out_path}")

    return 0


# ============================================================================
# live — real bridge vs. native-client parallel capture
# ============================================================================


def cmd_live(args: argparse.Namespace) -> int:
    _maybe_reexec_bridge_python()
    from tools.color_fidelity.run_audit import main as run_audit_main  # noqa: E402

    out_dir = args.out or "compare_render_live"
    argv = [
        "--bridge-url", args.bridge,
        "--bridge-host", args.bridge_host,
        "--native-carla-host", args.carla,
        "--frames", str(args.frames),
        "--skip-codecs",
        "--out", out_dir,
    ]
    return run_audit_main(argv)


def cmd_match_frustum(args: argparse.Namespace) -> int:
    _maybe_reexec_bridge_python()
    bridge_http = f"http://{args.bridge_host}"
    out_dir = Path(args.out or "compare_render_match_frustum")
    out_dir.mkdir(parents=True, exist_ok=True)

    session = _poll_json(
        f"{bridge_http}/api/realtime/session",
        lambda snap: bool(snap.get("session_ready")) and snap.get("default_camera_id") is not None,
        timeout_s=45.0,
        interval_s=1.0,
    )
    camera_id = int(args.camera_id or session.get("default_camera_id") or 0)
    if camera_id <= 0:
        print("ERROR: no managed camera id available; pass --camera-id explicitly")
        return 2

    metrics_rows: list[dict[str, float | int | str]] = []
    try:
        try:
            pause_resp = _http_post_json(f"{bridge_http}/api/simulation/pause", {})
            print(
                "paused simulation:",
                f"sync_mode={pause_resp.get('sync_mode')} fixed_delta={pause_resp.get('fixed_delta')}"
            )
        except urllib.error.HTTPError as exc:
            print(f"ERROR: pause failed: {exc}")
            return 2

        frame_count = max(1, int(args.frames))
        pose = _source_camera_pose(args.carla, camera_id)
        pose_param = ",".join(f"{value:.6f}" for value in pose)
        browser_url = args.web_url or f"http://127.0.0.1:58336/?view=threejs&camPose={pose_param}"
        debug_key = args.debug_key or ("__camPoseDebug" if args.web_url is None else "")
        browser_captures: list[dict] = []
        for idx in range(frame_count):
            web_path = out_dir / f"web_{idx:03d}.png"
            capture = _capture_browser_canvas(
                page_url=browser_url,
                out_path=web_path,
                debug_key=debug_key,
                wait_ms=args.browser_wait_ms,
                timeout_ms=args.browser_timeout_ms,
            )
            debug_info = capture.get("debug") or {}
            if debug_key and not debug_info:
                capture = _capture_browser_canvas(
                    page_url=browser_url,
                    out_path=web_path,
                    debug_key=debug_key,
                    wait_ms=max(args.browser_wait_ms, 4000),
                    timeout_ms=args.browser_timeout_ms,
                )
                debug_info = capture.get("debug") or {}
            if debug_key == "__camPoseDebug" and not debug_info.get("applied", False):
                raise RuntimeError(f"browser camPose debug did not apply pose for camera {camera_id}: {capture}")
            if debug_key == "__camMatchDebug" and not debug_info.get("found", False):
                raise RuntimeError(f"browser camMatch debug did not resolve camera {camera_id}: {capture}")
            browser_captures.append(capture)
        native_frames = _capture_native_shadow_frames(
            carla_host_port=args.carla,
            source_camera_id=camera_id,
            frames=frame_count,
            out_dir=out_dir,
        )

        for idx in range(frame_count):
            capture = browser_captures[idx]
            web_path = Path(str(capture["path"]))
            ue5 = native_frames[min(idx, len(native_frames) - 1)]
            row = _image_metrics(web_path, Path(ue5["path"]))
            failures = _target_failures(row)
            row.update(
                {
                    "frame": idx,
                    "camera_id": camera_id,
                    "bridge_default_camera_id": int(session.get("default_camera_id") or 0),
                    "browser_url": browser_url,
                    "comparison_scope": "managed default RGB camera only",
                    "ue5_frame": int(ue5["frame"]),
                    "source_pose": pose_param,
                    "target_failures": ";".join(failures) if failures else "",
                    "target_status": "passes_subset_targets" if not failures else "below_subset_targets",
                }
            )
            metrics_rows.append(row)
    finally:
        try:
            _http_post_json(f"{bridge_http}/api/simulation/play", {})
        except Exception:
            pass

    csv_path = out_dir / "metrics.csv"
    with csv_path.open("w", newline="") as f:
        fieldnames = [
            "frame",
            "camera_id",
            "bridge_default_camera_id",
            "ue5_frame",
            "width",
            "height",
            "deltae76_mean_full_frame",
            "deltae76_p95_full_frame",
            "ssim_luma",
            "psnr_db",
            "hist_intersection_luma_64",
            "mean_err_r",
            "mean_err_g",
            "mean_err_b",
            "comparison_scope",
            "target_status",
            "target_failures",
            "browser_url",
            "source_pose",
            "web_path",
            "ue5_path",
        ]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(metrics_rows)

    mean_de = statistics.mean(float(row["deltae76_mean_full_frame"]) for row in metrics_rows)
    mean_psnr = statistics.mean(float(row["psnr_db"]) for row in metrics_rows)
    mean_ssim = statistics.mean(float(row["ssim_luma"]) for row in metrics_rows)
    summary = {
        "camera_id": camera_id,
        "frames": frame_count,
        "scope": "single managed RGB camera only",
        "mean_deltae76_full_frame": mean_de,
        "mean_psnr_db": mean_psnr,
        "mean_ssim_luma": mean_ssim,
        "thresholds": {
            "deltae76_mean_full_frame_max": 1.0,
            "deltae76_p95_full_frame_max": 3.0,
            "ssim_luma_min": 0.97,
            "psnr_db_min": 32.0,
            "hist_intersection_luma_64_min": 0.92,
        },
        "passes_subset_targets": all(not row["target_failures"] for row in metrics_rows),
        "failed_metrics": sorted({failure for row in metrics_rows for failure in str(row["target_failures"]).split(";") if failure}),
        "metrics_csv": str(csv_path),
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2))
    print(json.dumps(summary, indent=2))
    print(f"wrote {csv_path}")
    return 0


def cmd_regress(args: argparse.Namespace) -> int:
    baseline_path = Path(args.baseline)
    new_path = Path(args.new)
    baseline_rows = _read_csv_rows(baseline_path)
    new_rows = _read_csv_rows(new_path)
    failures = _regression_failures(
        baseline_rows,
        new_rows,
        deltae_mean_tol=args.deltae_mean_tol,
        deltae_p95_tol=args.deltae_p95_tol,
        ssim_tol=args.ssim_tol,
        psnr_tol=args.psnr_tol,
        hist_tol=args.hist_tol,
    )
    if failures:
        print("REGRESSION FAILURES:")
        for failure in failures:
            print(f" - {failure}")
        return 1
    print(
        "OK: no metric regressions detected",
        f"(baseline={baseline_path} new={new_path})",
    )
    return 0


# ============================================================================
# CLI
# ============================================================================


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="compare_render",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = p.add_subparsers(dest="command")

    s = sub.add_parser("stats", help="legacy three vs. ue5 histogram compare")
    s.add_argument("threejs_png")
    s.add_argument("ue5_jpg")
    s.set_defaults(func=cmd_stats)

    s = sub.add_parser("test-pattern", help="BGRA→JPEG round-trip sanity")
    s.add_argument("--backend", default="auto", choices=["auto", "turbojpeg", "pillow"])
    s.add_argument("--quality", type=int, default=95)
    s.set_defaults(func=cmd_test_pattern)

    s = sub.add_parser("depth-roundtrip", help="CARLA depth encode/decode numeric check")
    s.set_defaults(func=cmd_depth_roundtrip)

    s = sub.add_parser("palette-diff", help="diff our palette vs CARLA's header")
    s.set_defaults(func=cmd_palette_diff)

    s = sub.add_parser("jpeg-sweep", help="quality/subsampling curve")
    s.add_argument("--quality", default="60,75,85,95")
    s.add_argument("--input", default=None,
                   help="reference RGB image; synthetic road pattern if omitted")
    s.add_argument("--csv", default=None, help="write results CSV here")
    s.set_defaults(func=cmd_jpeg_sweep)

    s = sub.add_parser("live", help="run the color-fidelity audit live/wire-equivalent path")
    s.add_argument("--bridge", default="ws://127.0.0.1:58337/ws")
    s.add_argument("--bridge-host", default="127.0.0.1:58337")
    s.add_argument("--carla", default="127.0.0.1:58338")
    s.add_argument("--frames", type=int, default=20)
    s.add_argument("--out", default=None, help="output directory for live audit artifacts")
    s.set_defaults(func=cmd_live)

    s = sub.add_parser(
        "match-frustum",
        help="capture browser canvas vs a native shadow camera for the managed RGB camera",
    )
    s.add_argument("--bridge-host", default="127.0.0.1:58337")
    s.add_argument("--carla", default="127.0.0.1:58338")
    s.add_argument("--camera-id", type=int, default=None,
                   help="override managed camera actor id; defaults to /api/realtime/session default_camera_id")
    s.add_argument("--web-url", default=None,
                   help="browser URL to capture; defaults to http://127.0.0.1:58336/?camPose=<source-camera-world-pose>")
    s.add_argument("--debug-key", default=None,
                   help="optional browser debug global to wait on (defaults to __camPoseDebug for the built-in URL)")
    s.add_argument("--frames", type=int, default=4)
    s.add_argument("--browser-wait-ms", type=int, default=2500)
    s.add_argument("--browser-timeout-ms", type=int, default=20000)
    s.add_argument("--out", default=None, help="output directory for paired artifacts + metrics.csv")
    s.set_defaults(func=cmd_match_frustum)

    s = sub.add_parser("regress", help="diff two compare_render CSVs and fail on metric regression")
    s.add_argument("--baseline", required=True)
    s.add_argument("--new", required=True)
    s.add_argument("--deltae-mean-tol", type=float, default=0.0)
    s.add_argument("--deltae-p95-tol", type=float, default=0.0)
    s.add_argument("--ssim-tol", type=float, default=0.0)
    s.add_argument("--psnr-tol", type=float, default=0.0)
    s.add_argument("--hist-tol", type=float, default=0.0)
    s.set_defaults(func=cmd_regress)

    return p


def main(argv: list[str]) -> int:
    # Back-compat: `compare_render.py a.png b.jpg` still means `stats`.
    if len(argv) == 3 and all(not a.startswith("-") for a in argv[1:]):
        ns = argparse.Namespace(threejs_png=argv[1], ue5_jpg=argv[2])
        return cmd_stats(ns)
    parser = build_parser()
    args = parser.parse_args(argv[1:])
    if not getattr(args, "func", None):
        parser.print_help()
        return 2
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
